### ISSUE TITLE
why not text_embedding

### ISSUE THREAD

**Issue by hdmjdp** [imdanboy/jets#1]
https://github.com/imdanboy/jets/blob/4d5ae143050c8031c61ec5482aed6216c07aacc9/espnet2/gan_tts/jets/generator.py#L592

In your paper, you refer "hs" to text_embedding, not encoder_out.

**Comment by imdanboy** [comment]
I intend to use an encoder_out as text_embedding; the purpose of the encoder was to encoding the text as text embedding.
It follows the structure of alignment learning framework as in [https://arxiv.org/abs/2108.10447](https://arxiv.org/abs/2108.10447)
